server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://dpg-d2n56fqli9vc73bnvas0-a.oregon-postgres.render.com:5432/creditya_db?sslmode=require
    username: creditya_db_user
    password: NxQrf1h15WeUU61fVpAFRersiAuGQQSf

  flyway:
    enabled: true
    url: jdbc:postgresql://dpg-d2n56fqli9vc73bnvas0-a.oregon-postgres.render.com:5432/creditya_db?sslmode=require
    user: creditya_db_user
    password: NxQrf1h15WeUU61fVpAFRersiAuGQQSf
    baseline-on-migrate: true
    locations: classpath:db/migration
    mixed: true
    connect-retries: 3
    validate-on-migrate: false

  main:
    banner-mode: console

logging:
  level:
    org.flywaydb: info
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
